### PR TITLE
wayland: Fix initial black screen due to size of 0x0

### LINKED ISSUE #293: Imv considers window size 0x0 unless explicitly set by compositor
I can’t tell for sure it’s `imv` bug as the compositor this happens in ([kiwmi](https://github.com/buffet/kiwmi)) is pretty much WIP & in other I don’t know what’s happening there (e.g. Sway definitely resizes it). In Wayfire the bug also occurs, just the window is resized from its visible size.

So, the bug:
* when I just run `imv image.png` w/o any config, its window has the screen size & is black. Holding `i` has no effect on this, pressing `:` doesn’t show anything (but `:q` quits `imv`). ~~I can resize the window but nothing changes\*~~
* when I add default size (half size of my screen) in `imv` config & run `imv image.png`, nothing changes except for the window size
* when I add a special case in `kiwmi` config to resize the window (to half the screen size) before showing it, it works as expected

~~\*actually, now I’ve tried once again & it worked when I resized it to something like 100x50px, but I can’t tell what exactly I was doing because I saw almost nothing (because of a general issue with `kiwmi`)~~

Edit: Resizing the window can be done at any time. ~~What I said before (& striked out) is probably because of another `kiwmi` (or my config) bug.~~

Another edit: oh wait, no. It’s pretty simple: `imv` sets its size to 0x0 (so when I try to resize it, I have to *enlarge* it — this is what I thought was a kiwmi bug), but renders a black rectangle of the expected size.

And yet another edit: Today after trying it in WF, I run it once again in kiwmi. This time it worked well except for resizing (which went from 0x0)

### PR DESCRIPTION
**Pull request by soreau**
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/master/stable/xdg-shell/xdg-shell.xml#L1037
states regarding xdg_toplevel.configure "The width and height arguments specify a hint to the window". imv
was using these dimensions even if they are 0x0, which is valid for the compositor to send. Clearly this is
a bad hint and should be ignored. This patch does that, and fixes #293.

### CODE REVIEW

File: src/wl_window.c [hunk 1]
```diff
@@ -610,8 +610,12 @@ static void toplevel_configure(void *data, struct xdg_toplevel *toplevel,
   (void)toplevel;
 
   struct imv_window *window = data;
-  window->width = width;
-  window->height = height;
+
+  if (width > 0 && height > 0)
```
Comment (eXeC64) [inline src/wl_window.c:614]: Can you merge lines 614 and 615 to match the style of the other `if` statements. Otherwise this looks good. Thanks for the PR.

**Comment by eXeC64** [comment]
Thanks!

**Comment by tiosgz** [comment]
Thank you, it works as expected! (I mean, kiwmi still considers it 0x0, but that’s OK as the image is now perfectly visible)

@eXeC64 Sorry for opening #293, somehow I hadn’t noticed that #292 had had the same issue.
